version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: izin-db
    environment:
      POSTGRES_DB: izin
      POSTGRES_USER: izin_user
      POSTGRES_PASSWORD: izin_pass_2024
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
